### ISSUE TITLE
Alias not working

### ISSUE THREAD

**Issue by Aslam97** [Aslam97/laravel-mix-vue-css-modules#3]
**Step to reproduce**

inside `<style>` import scss contain image url with alias 

**checkbox.scss**
```css
.test {
   background-image: url('~@assets/checkbox.png');
}
```

```vue
<style>
@import '@desing/checkbox.scss';
</style>
```
